### ISSUE TITLE
Cannot set property 'value' of null

### ISSUE THREAD

**Issue by mstorus** [agzam/jira-okta-puppet#2]
After running `npm run run`, I see Chromium gets launched to the correct Okta verification page, but the Username and Password fields do not get filled it.

In Terminal I see the output:

```
npm run run

> @ run /Users/mstorus/src/jira-okta-puppet
> node ./target/node/dev/dev-main.js

Let's go!
launching browser
arguments  #{/Users/mstorus/.nvm/versions/node/v12.14.1/bin/node /Users/mstorus/src/jira-okta-puppet/target/node/dev/dev-main.js}
logging in
decrypting username/pass
.. done
(node:12528) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot set property 'value' of null
    at __puppeteer_evaluation_script__:1:52
    at ExecutionContext._evaluateInternal (/Users/mstorus/src/jira-okta-puppet/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async ExecutionContext.evaluate (/Users/mstorus/src/jira-okta-puppet/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/mstorus/src/jira-okta-puppet/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/mstorus/src/jira-okta-puppet/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/mstorus/src/jira-okta-puppet/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/mstorus/src/jira-okta-puppet/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/mstorus/src/jira-okta-puppet/node_modules/puppeteer/lib/helper.js:112:23)
    at jira_auth.core.clear_input (/Users/mstorus/src/jira-okta-puppet/target/node/dev/dev-main.js:3397:173)
    at /Users/mstorus/src/jira-okta-puppet/target/node/dev/dev-main.js:3399:104
    at /Users/mstorus/src/jira-okta-puppet/target/node/dev/dev-main.js:2272:401
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I verified in the Chromium console that `document.querySelector('input[id=okta-signin-username]')` and `document.querySelector('input[id=okta-signin-password]')` return the correct elements

**Comment by agzam** [comment]
Oh wow... Sorry, for a very late reply. I honestly didn't expect anyone using this.
You probably missed the credentials step, no?
 
https://github.com/agzam/jira-okta-puppet#for-this-script-to-work-youre-gonna-need-to
